version: '2'

services:
  nginx:
    image: nginx
    links:
      - api
    ports:
      - "80"
    volumes:
      - ./website/build:/usr/share/nginx/html/website
      - ./editor/build:/usr/share/nginx/html/editor
      - ./nginx.conf:/etc/nginx/nginx.conf
  api:
    image: node
    volumes:
      - ./api/build:/app/
    working_dir: /app/
    command: npm start
    ports:
      - "80"
    links:
      - mongodb
  mongodb:
    image: mongo
    expose:
      - "80"
    volumes:
      - /data/db