version: '2'

services:
  nginx:
    image: nginx
    links:
      - api
    ports:
      - "80:80"
    volumes:
      - ./website:/usr/share/nginx/html/website
      - ./editor:/usr/share/nginx/html/editor
      - ./nginx.conf:/etc/nginx/nginx.conf
  api:
    image: node
    volumes:
      - ./api/:/app/
    working_dir: /app/
    environment:
      - NODE_ENV=$${NODE_ENV}
      - TWITTER_CONSUMER_KEY=$${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=$${TWITTER_CONSUMER_SECRET}
      - PIXORE_SECRET=$${PIXORE_SECRET}
      - AWS_ACCESS_KEY_ID=$${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=$${AWS_SECRET_ACCESS_KEY}
    command: yarn run start:simple
    expose:
      - "80"
    links:
      - mongodb
  mongodb:
    image: mongo
    expose:
      - "80"
    volumes:
      - /data/db